import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@/shared/styles/globals.css';
import { Toaster } from 'sonner';
import SlideTransition from '@/features/transitionNavigate/components/SlideTransition';
import Header from '@/shared/components/layout/header/Header';
import { SessionProvider } from 'next-auth/react';
import { auth } from '@/shared/lib/auth';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <SlideTransition>
            <Header session={session} />
            {children}
          </SlideTransition>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
